> nextn@0.1.0 build > tsc --noEmit && next build
src/app/room/[roomId]/page.tsx:355:34 - error TS2352: Conversion of type 'Record<Language, string>' to type '"title" | "idCopiedToastTitle" | "joinHere" | "chatLoginMessage" | "leaveRoomButton" | "timeLeftLabel" | "copyRoomLinkButton" | "playerListTitle" | "addFriendButton" | "onlineStatus" | ... 45 more ... | "playerHasNotSubmitted"' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

355         toast({ title: translate(UI_TEXTS.errorToastTitle as keyof typeof ROOM_TEXTS), description: "No se pudieron cargar los mensajes.", variant: "destructive"});
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/app/room/[roomId]/page.tsx:411:33 - error TS2352: Conversion of type 'Record<Language, string>' to type '"title" | "idCopiedToastTitle" | "joinHere" | "chatLoginMessage" | "leaveRoomButton" | "timeLeftLabel" | "copyRoomLinkButton" | "playerListTitle" | "addFriendButton" | "onlineStatus" | ... 45 more ... | "playerHasNotSubmitted"' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

411         toast({title: translate(UI_TEXTS.errorToastTitle as keyof typeof ROOM_TEXTS), description: "No se pudieron enviar tus respuestas.", variant: "destructive"});
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/app/room/[roomId]/page.tsx:699:38 - error TS2352: Conversion of type 'Record<Language, string>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

699       toast({ title: commonTranslate(UI_TEXTS.chatLoginTitle as keyof typeof UI_TEXTS), description: commonTranslate(UI_TEXTS.chatLoginMessage as keyof typeof UI_TEXTS), variant: "destructive" });
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/app/room/[roomId]/page.tsx:699:118 - error TS2352: Conversion of type 'Record<Language, string>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

699       toast({ title: commonTranslate(UI_TEXTS.chatLoginTitle as keyof typeof UI_TEXTS), description: commonTranslate(UI_TEXTS.chatLoginMessage as keyof typeof UI_TEXTS), variant: "destructive" });
                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/app/room/[roomId]/page.tsx:716:32 - error TS2352: Conversion of type 'Record<Language, string>' to type '"title" | "idCopiedToastTitle" | "joinHere" | "chatLoginMessage" | "leaveRoomButton" | "timeLeftLabel" | "copyRoomLinkButton" | "playerListTitle" | "addFriendButton" | "onlineStatus" | ... 45 more ... | "playerHasNotSubmitted"' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

716       toast({ title: translate(UI_TEXTS.errorToastTitle as keyof typeof ROOM_TEXTS), description: "No se pudo enviar tu mensaje.", variant: "destructive" });
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 5 errors in the same file, starting at: src/app/room/[roomId]/page.tsx:355