> nextn@0.1.0 build > tsc --noEmit && next build
src/app/page.tsx:1130:11 - error TS2322: Type '{ messages: ChatMessage[]; onSendMessage: (text: string) => void; isOpen: boolean; setIsOpen: Dispatch<SetStateAction<boolean>>; currentUserUid: string | undefined; currentUserName: string; currentUserAvatar: string | ... 1 more ... | undefined; language: Language; currentRoomId: null; }' is not assignable to type 'IntrinsicAttributes & ChatPanelProps'.
  Property 'currentRoomId' does not exist on type 'IntrinsicAttributes & ChatPanelProps'.

1130           currentRoomId={null} // This chat panel on main page is not tied to a DB room
               ~~~~~~~~~~~~~

src/app/room/[roomId]/page.tsx:983:11 - error TS2322: Type '{ messages: ChatMessage[]; onSendMessageDB: (text: string) => void; isOpen: boolean; setIsOpen: Dispatch<SetStateAction<boolean>>; currentUserUid: string; currentUserName: string; currentUserAvatar: string | null; language: Language; currentRoomId: string; }' is not assignable to type 'IntrinsicAttributes & ChatPanelProps'.
  Property 'onSendMessageDB' does not exist on type 'IntrinsicAttributes & ChatPanelProps'. Did you mean 'onSendMessage'?

983           onSendMessageDB={handleSendChatMessageInRoom} // Use DB sending if in a room
              ~~~~~~~~~~~~~~~

Found 2 errors in 2 files.

Errors  Files
     1  src/app/page.tsx:1130